spring:
  datasource:
    url: jdbc:postgresql://tu_url:tu_puerto/nombre_bbdd
    username: tu_usuario
    password: tu_contaseña
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true